/**
 * DEECA Wildlife Code Book - species name to numeric species code mapping,
 * for use on Wildlife Shelter Record Sheets in Victoria.
 *
 * Source: https://www.vic.gov.au/sites/default/files/2020-12/Wildlife_Code_Book.doc
 * (linked from https://www.vic.gov.au/wildlife-rehabilitation-shelters-and-foster-carers)
 *
 * NOTE: This is transcribed from the published Wildlife Code Book and covers
 * mammals, a substantial common-species subset of birds, and reptiles &
 * amphibians. The book is periodically updated by DEECA - species not found
 * here should be entered with the WildTrack360 species name as-is and the
 * DEECA species code left blank (per the Code Book's own instructions for
 * unidentified/uncertain species), then reconciled against the latest Code
 * Book download before an annual/audit export.
 */

export interface VicSpeciesCodeEntry {
  commonName: string;
  code: string;
  group: 'mammal' | 'bird' | 'reptile-amphibian';
}

export const VIC_SPECIES_CODES: VicSpeciesCodeEntry[] = [
  // ─── Mammals: Monotremes ──────────────────────────────────────────────
  { commonName: 'Platypus', code: '1001', group: 'mammal' },
  { commonName: 'Short-beaked Echidna', code: '1003', group: 'mammal' },

  // ─── Mammals: Dasyurids ───────────────────────────────────────────────
  { commonName: 'Antechinus, Brown', code: '1028', group: 'mammal' },
  { commonName: 'Antechinus, Dusky', code: '1033', group: 'mammal' },
  { commonName: 'Antechinus, Swamp', code: '1034', group: 'mammal' },
  { commonName: 'Antechinus, Yellow-footed', code: '1027', group: 'mammal' },
  { commonName: 'Dunnart, Common', code: '1061', group: 'mammal' },
  { commonName: 'Dunnart, Fat-tailed', code: '1072', group: 'mammal' },
  { commonName: 'Dunnart, White-footed', code: '1069', group: 'mammal' },
  { commonName: 'Ningaui, Mallee', code: '1055', group: 'mammal' },
  { commonName: 'Paucident Planigale', code: '1050', group: 'mammal' },
  { commonName: 'Phascogale, Brush-tailed', code: '1017', group: 'mammal' },
  { commonName: 'Quoll, Eastern', code: '1009', group: 'mammal' },
  { commonName: 'Quoll, Tiger', code: '1008', group: 'mammal' },
  { commonName: 'Unidentified Antechinus', code: '1817', group: 'mammal' },
  { commonName: 'Unidentified Sminthopsis', code: '1800', group: 'mammal' },
  { commonName: 'Unidentified Quoll', code: '1824', group: 'mammal' },

  // ─── Mammals: Bandicoots ──────────────────────────────────────────────
  { commonName: 'Eastern Barred Bandicoot', code: '1098', group: 'mammal' },
  { commonName: 'Southern Brown Bandicoot', code: '1092', group: 'mammal' },
  { commonName: 'Long-nosed Bandicoot', code: '1097', group: 'mammal' },
  { commonName: 'Unidentified Bandicoot', code: '1801', group: 'mammal' },

  // ─── Mammals: Rat Kangaroos ───────────────────────────────────────────
  { commonName: 'Long-footed Potoroo', code: '1179', group: 'mammal' },
  { commonName: 'Long-nosed Potoroo', code: '1175', group: 'mammal' },
  { commonName: 'Unidentified Potoroo', code: '1806', group: 'mammal' },

  // ─── Mammals: Kangaroos and Wallabies ─────────────────────────────────
  { commonName: 'Brush-tailed Rock-wallaby', code: '1215', group: 'mammal' },
  { commonName: 'Common Wallaroo', code: '1266', group: 'mammal' },
  { commonName: 'Eastern Grey Kangaroo', code: '1265', group: 'mammal' },
  { commonName: 'Red Kangaroo', code: '1275', group: 'mammal' },
  { commonName: 'Red-necked Wallaby', code: '1261', group: 'mammal' },
  { commonName: 'Swamp Wallaby', code: '1242', group: 'mammal' },
  { commonName: 'Western Grey Kangaroo', code: '1263', group: 'mammal' },
  { commonName: 'Unidentified Kangaroo', code: '1805', group: 'mammal' },

  // ─── Mammals: Koala & Wombats ─────────────────────────────────────────
  { commonName: 'Common Wombat', code: '1165', group: 'mammal' },
  { commonName: 'Koala', code: '1162', group: 'mammal' },

  // ─── Mammals: Flying-foxes ────────────────────────────────────────────
  { commonName: 'Grey-headed Flying-fox', code: '1280', group: 'mammal' },
  { commonName: 'Little Red Flying-fox', code: '1281', group: 'mammal' },
  { commonName: 'Unidentified Flying-fox', code: '1807', group: 'mammal' },

  // ─── Mammals: Bats ────────────────────────────────────────────────────
  { commonName: 'Eastern Horseshoe-bat', code: '1303', group: 'mammal' },
  { commonName: 'Yellow-bellied Sheathtail-bat', code: '1321', group: 'mammal' },
  { commonName: 'Little Mastiff-bat', code: '1326', group: 'mammal' },
  { commonName: 'Unidentified Mastiff-bat', code: '1815', group: 'mammal' },
  { commonName: "Mormopterus sp. (big penis)", code: '1808', group: 'mammal' },
  { commonName: "Mormopterus sp. (little penis)", code: '1809', group: 'mammal' },
  { commonName: 'White-striped Mastiff-bat', code: '1324', group: 'mammal' },
  { commonName: 'Chocolate Wattled Bat', code: '1351', group: 'mammal' },
  { commonName: "Gould's Wattled Bat", code: '1349', group: 'mammal' },
  { commonName: 'Unidentified Wattled Bat', code: '1325', group: 'mammal' },
  { commonName: 'Common Bent-wing Bat', code: '1341', group: 'mammal' },
  { commonName: 'Eptesicus baverstocki', code: '1819', group: 'mammal' },
  { commonName: 'King River Eptesicus', code: '1378', group: 'mammal' },
  { commonName: "Large-footed Myotis", code: '1357', group: 'mammal' },
  { commonName: 'Large Forest Eptesicus', code: '1381', group: 'mammal' },
  { commonName: 'Little Forest Eptesicus', code: '1379', group: 'mammal' },
  { commonName: 'Unidentified Eptesicus', code: '1810', group: 'mammal' },
  { commonName: 'Eastern Broad-nosed Bat', code: '1811', group: 'mammal' },
  { commonName: "Gould's Long-eared Bat", code: '1334', group: 'mammal' },
  { commonName: 'Greater Long-eared Bat', code: '1332', group: 'mammal' },
  { commonName: 'Great Pipistrelle', code: '1372', group: 'mammal' },
  { commonName: 'Lesser Long-eared Bat', code: '1335', group: 'mammal' },
  { commonName: 'Western Broad-nosed Bat', code: '1364', group: 'mammal' },
  { commonName: 'Unidentified Broad-nosed Bat', code: '1812', group: 'mammal' },
  { commonName: 'Unidentified Long-eared Bat', code: '1816', group: 'mammal' },

  // ─── Mammals: Brushtail Possums ───────────────────────────────────────
  { commonName: 'Common Brushtail Possum', code: '1113', group: 'mammal' },
  { commonName: 'Mountain Brushtail Possum', code: '1115', group: 'mammal' },
  { commonName: 'Unidentified Brushtail Possum', code: '1802', group: 'mammal' },

  // ─── Mammals: Pygmy-possums ───────────────────────────────────────────
  { commonName: 'Eastern Pygmy-possum', code: '1150', group: 'mammal' },
  { commonName: 'Feathertail Glider', code: '1147', group: 'mammal' },
  { commonName: 'Little Pygmy-possum', code: '1152', group: 'mammal' },
  { commonName: 'Mountain Pygmy-possum', code: '1156', group: 'mammal' },
  { commonName: 'Western Pygmy-possum', code: '1151', group: 'mammal' },
  { commonName: 'Unidentified Pygmy-possum', code: '1803', group: 'mammal' },

  // ─── Mammals: Gliders and Ringtails ───────────────────────────────────
  { commonName: 'Common Ringtail Possum', code: '1129', group: 'mammal' },
  { commonName: 'Greater Glider', code: '1133', group: 'mammal' },
  { commonName: "Leadbeater's Possum", code: '1141', group: 'mammal' },
  { commonName: 'Squirrel Glider', code: '1137', group: 'mammal' },
  { commonName: 'Sugar Glider', code: '1138', group: 'mammal' },
  { commonName: 'Yellow-bellied Glider', code: '1136', group: 'mammal' },
  { commonName: 'Unidentified Glider', code: '1804', group: 'mammal' },

  // ─── Mammals: Rats and Mice ───────────────────────────────────────────
  { commonName: 'Black Rat', code: '1408', group: 'mammal' },
  { commonName: 'Broad-toothed Rat', code: '1438', group: 'mammal' },
  { commonName: 'Brown Rat', code: '1409', group: 'mammal' },
  { commonName: 'Bush Rat', code: '1395', group: 'mammal' },
  { commonName: 'House Mouse', code: '1412', group: 'mammal' },
  { commonName: 'Heath Mouse', code: '1468', group: 'mammal' },
  { commonName: "Mitchell's Hopping-mouse", code: '1480', group: 'mammal' },
  { commonName: 'New Holland Mouse', code: '1455', group: 'mammal' },
  { commonName: 'Silky Mouse', code: '1457', group: 'mammal' },
  { commonName: 'Smoky Mouse', code: '1458', group: 'mammal' },
  { commonName: 'Swamp Rat', code: '1398', group: 'mammal' },
  { commonName: 'Water Rat', code: '1415', group: 'mammal' },
  { commonName: 'Unidentified Pseudomys', code: '1813', group: 'mammal' },
  { commonName: 'Unidentified Rattus', code: '1818', group: 'mammal' },
  { commonName: 'Unidentified Small Rodent', code: '1820', group: 'mammal' },

  // ─── Mammals: Introduced Herbivores & Marine Mammals ─────────────────
  { commonName: 'Fallow Deer', code: '1523', group: 'mammal' },
  { commonName: 'Red Deer', code: '1526', group: 'mammal' },
  { commonName: 'Hog Deer', code: '1525', group: 'mammal' },
  { commonName: 'Sambar', code: '1527', group: 'mammal' },
  { commonName: 'Unidentified Deer', code: '1814', group: 'mammal' },
  { commonName: 'Australian Fur-Seal', code: '1542', group: 'mammal' },
  { commonName: 'Australian Sea-lion', code: '1539', group: 'mammal' },
  { commonName: 'New Zealand Fur-Seal', code: '1543', group: 'mammal' },
  { commonName: 'Crab-eater Seal', code: '1555', group: 'mammal' },
  { commonName: 'Leopard Seal', code: '1549', group: 'mammal' },
  { commonName: 'Southern Elephant Seal', code: '1546', group: 'mammal' },
  { commonName: 'Bottlenose Dolphin', code: '1612', group: 'mammal' },
  { commonName: 'Common Dolphin', code: '1616', group: 'mammal' },
  { commonName: 'False Killer Whale', code: '1603', group: 'mammal' },
  { commonName: "Fraser's Dolphin", code: '1624', group: 'mammal' },
  { commonName: 'Killer Whale', code: '1600', group: 'mammal' },
  { commonName: 'Long-finned Pilot Whale', code: '1606', group: 'mammal' },
  { commonName: "Risso's Dolphin", code: '1609', group: 'mammal' },

  // ─── Birds (common-species subset) ────────────────────────────────────
  { commonName: 'Emu', code: '1', group: 'bird' },
  { commonName: 'Malleefowl', code: '7', group: 'bird' },
  { commonName: 'Little Penguin', code: '5', group: 'bird' },
  { commonName: 'Australian Wood Duck (Maned Duck)', code: '202', group: 'bird' },
  { commonName: 'Pacific Black Duck', code: '208', group: 'bird' },
  { commonName: 'Musk Duck', code: '217', group: 'bird' },
  { commonName: 'Australian Shelduck', code: '207', group: 'bird' },
  { commonName: 'Cape Barren Goose', code: '198', group: 'bird' },
  { commonName: 'Black Swan', code: '203', group: 'bird' },
  { commonName: 'Australian White Ibis (Sacred Ibis)', code: '179', group: 'bird' },
  { commonName: 'Straw-necked Ibis', code: '180', group: 'bird' },
  { commonName: 'Royal Spoonbill', code: '181', group: 'bird' },
  { commonName: 'Great Egret', code: '187', group: 'bird' },
  { commonName: 'White-faced Heron', code: '188', group: 'bird' },
  { commonName: 'Pacific Heron', code: '189', group: 'bird' },
  { commonName: 'Nankeen Night Heron (Rufous Night Heron)', code: '192', group: 'bird' },
  { commonName: 'Australian Pelican', code: '106', group: 'bird' },
  { commonName: 'Great Cormorant', code: '96', group: 'bird' },
  { commonName: 'Little Black Cormorant', code: '97', group: 'bird' },
  { commonName: 'Little Pied Cormorant', code: '100', group: 'bird' },
  { commonName: 'Pied Cormorant', code: '99', group: 'bird' },
  { commonName: 'Darter', code: '101', group: 'bird' },
  { commonName: 'Wedge-tailed Eagle', code: '224', group: 'bird' },
  { commonName: 'Little Eagle', code: '225', group: 'bird' },
  { commonName: 'White-bellied Sea-Eagle', code: '226', group: 'bird' },
  { commonName: 'Brown Goshawk', code: '221', group: 'bird' },
  { commonName: 'Grey Goshawk', code: '220', group: 'bird' },
  { commonName: 'Collared Sparrowhawk', code: '222', group: 'bird' },
  { commonName: 'Black Kite', code: '229', group: 'bird' },
  { commonName: 'Black-shouldered Kite', code: '232', group: 'bird' },
  { commonName: 'Whistling Kite', code: '228', group: 'bird' },
  { commonName: 'Swamp Harrier', code: '219', group: 'bird' },
  { commonName: 'Spotted Harrier', code: '218', group: 'bird' },
  { commonName: 'Nankeen Kestrel (Australian Kestrel)', code: '240', group: 'bird' },
  { commonName: 'Brown Falcon', code: '239', group: 'bird' },
  { commonName: 'Peregrine Falcon', code: '237', group: 'bird' },
  { commonName: 'Australian Hobby', code: '235', group: 'bird' },
  { commonName: 'Southern Boobook', code: '242', group: 'bird' },
  { commonName: 'Barn Owl', code: '249', group: 'bird' },
  { commonName: 'Masked Owl', code: '250', group: 'bird' },
  { commonName: 'Powerful Owl', code: '248', group: 'bird' },
  { commonName: 'Sooty Owl', code: '253', group: 'bird' },
  { commonName: 'Tawny Frogmouth', code: '313', group: 'bird' },
  { commonName: 'Australian Owlet-nightjar', code: '317', group: 'bird' },
  { commonName: 'Sulphur-crested Cockatoo', code: '269', group: 'bird' },
  { commonName: 'Galah', code: '273', group: 'bird' },
  { commonName: 'Gang-gang Cockatoo', code: '268', group: 'bird' },
  { commonName: 'Long-billed Corella', code: '272', group: 'bird' },
  { commonName: 'Little Corella', code: '271', group: 'bird' },
  { commonName: 'Yellow-tailed Black-Cockatoo', code: '267', group: 'bird' },
  { commonName: 'Rainbow Lorikeet', code: '254', group: 'bird' },
  { commonName: 'Musk Lorikeet', code: '258', group: 'bird' },
  { commonName: 'Little Lorikeet', code: '260', group: 'bird' },
  { commonName: 'Purple-crowned Lorikeet', code: '259', group: 'bird' },
  { commonName: 'Australian King-Parrot', code: '281', group: 'bird' },
  { commonName: 'Crimson Rosella', code: '282', group: 'bird' },
  { commonName: 'Eastern Rosella', code: '288', group: 'bird' },
  { commonName: 'Yellow Rosella', code: '284', group: 'bird' },
  { commonName: 'Red-rumped Parrot', code: '295', group: 'bird' },
  { commonName: 'Blue Bonnet', code: '297', group: 'bird' },
  { commonName: 'Superb Parrot', code: '277', group: 'bird' },
  { commonName: 'Laughing Kookaburra', code: '322', group: 'bird' },
  { commonName: 'Sacred Kingfisher', code: '326', group: 'bird' },
  { commonName: 'Azure Kingfisher', code: '319', group: 'bird' },
  { commonName: 'Rainbow Bee-eater', code: '329', group: 'bird' },
  { commonName: 'Superb Lyrebird', code: '350', group: 'bird' },
  { commonName: 'Welcome Swallow', code: '357', group: 'bird' },
  { commonName: 'Tree Martin', code: '359', group: 'bird' },
  { commonName: 'Fairy Martin', code: '360', group: 'bird' },
  { commonName: 'Grey Fantail', code: '361', group: 'bird' },
  { commonName: 'Rufous Fantail', code: '362', group: 'bird' },
  { commonName: 'Willie Wagtail', code: '364', group: 'bird' },
  { commonName: 'Golden Whistler', code: '398', group: 'bird' },
  { commonName: 'Rufous Whistler', code: '401', group: 'bird' },
  { commonName: 'Grey Shrike-thrush', code: '408', group: 'bird' },
  { commonName: 'Australian Magpie-lark', code: '415', group: 'bird' },
  { commonName: 'Crested Shrike-tit', code: '416', group: 'bird' },
  { commonName: 'Eastern Whipbird', code: '421', group: 'bird' },
  { commonName: 'Black-faced Cuckoo-shrike', code: '424', group: 'bird' },
  { commonName: 'White-winged Chough', code: '693', group: 'bird' },
  { commonName: 'Australian Raven', code: '930', group: 'bird' },
  { commonName: 'Little Raven', code: '954', group: 'bird' },
  { commonName: 'Forest Raven', code: '868', group: 'bird' },
  { commonName: 'Australian Magpie', code: '705', group: 'bird' },
  { commonName: 'Grey Butcherbird', code: '702', group: 'bird' },
  { commonName: 'Pied Butcherbird', code: '700', group: 'bird' },
  { commonName: 'Pied Currawong', code: '694', group: 'bird' },
  { commonName: 'Grey Currawong', code: '697', group: 'bird' },
  { commonName: 'Little Crow', code: '691', group: 'bird' },
  { commonName: 'Noisy Miner', code: '634', group: 'bird' },
  { commonName: 'Bell Miner', code: '633', group: 'bird' },
  { commonName: 'New Holland Honeyeater', code: '631', group: 'bird' },
  { commonName: 'White-plumed Honeyeater', code: '625', group: 'bird' },
  { commonName: 'Red Wattlebird', code: '638', group: 'bird' },
  { commonName: 'Little Wattlebird', code: '637', group: 'bird' },
  { commonName: 'Noisy Friarbird', code: '645', group: 'bird' },
  { commonName: 'Silvereye', code: '574', group: 'bird' },
  { commonName: 'Superb Fairy-wren', code: '529', group: 'bird' },
  { commonName: 'Splendid Fairy-wren', code: '532', group: 'bird' },
  { commonName: 'Spotted Pardalote', code: '565', group: 'bird' },
  { commonName: 'Striated Pardalote', code: '976', group: 'bird' },
  { commonName: 'Common Starling', code: '999', group: 'bird' },
  { commonName: 'Mistletoebird', code: '564', group: 'bird' },
  { commonName: 'Eastern Yellow Robin', code: '392', group: 'bird' },
  { commonName: 'Scarlet Robin', code: '380', group: 'bird' },
  { commonName: 'Flame Robin', code: '382', group: 'bird' },
  { commonName: 'Zebra Finch', code: '653', group: 'bird' },
  { commonName: 'Red-browed Finch', code: '662', group: 'bird' },
  { commonName: 'Diamond Firetail', code: '652', group: 'bird' },
  { commonName: 'Satin Bowerbird', code: '679', group: 'bird' },
  { commonName: 'Australasian Grebe', code: '61', group: 'bird' },
  { commonName: 'Hoary-headed Grebe', code: '62', group: 'bird' },
  { commonName: 'Great Crested Grebe', code: '60', group: 'bird' },
  { commonName: 'Eurasian Coot', code: '59', group: 'bird' },
  { commonName: 'Purple Swamphen', code: '58', group: 'bird' },
  { commonName: 'Dusky Moorhen', code: '56', group: 'bird' },
  { commonName: 'Black-tailed Native-hen', code: '55', group: 'bird' },
  { commonName: 'Brolga', code: '177', group: 'bird' },
  { commonName: 'Australian Bustard', code: '176', group: 'bird' },
  { commonName: 'Masked Lapwing', code: '133', group: 'bird' },
  { commonName: 'Silver Gull', code: '125', group: 'bird' },
  { commonName: 'Pacific Gull', code: '126', group: 'bird' },
  { commonName: 'Kelp Gull', code: '981', group: 'bird' },
  { commonName: 'Crested Tern', code: '115', group: 'bird' },
  { commonName: 'Common Bronzewing', code: '34', group: 'bird' },
  { commonName: 'Brush Bronzewing', code: '35', group: 'bird' },
  { commonName: 'Crested Pigeon', code: '43', group: 'bird' },
  { commonName: 'Spotted Dove', code: '30', group: 'bird' },
  { commonName: 'Peaceful Dove', code: '30', group: 'bird' },
  { commonName: 'Wonga Pigeon', code: '44', group: 'bird' },

  // ─── Reptiles & Amphibians ─────────────────────────────────────────────
  { commonName: 'Alpine Tree Frog', code: '3307', group: 'reptile-amphibian' },
  { commonName: 'Green and Golden Grass Frog', code: '3166', group: 'reptile-amphibian' },
  { commonName: 'Growling Grass Frog', code: '3207', group: 'reptile-amphibian' },
  { commonName: 'Peron\'s Tree Frog', code: '3204', group: 'reptile-amphibian' },
  { commonName: 'Southern Brown Tree Frog', code: '3182', group: 'reptile-amphibian' },
  { commonName: 'Common Froglet', code: '3134', group: 'reptile-amphibian' },
  { commonName: 'Spotted Marsh Frog', code: '3063', group: 'reptile-amphibian' },
  { commonName: 'Striped Marsh Frog', code: '3061', group: 'reptile-amphibian' },
  { commonName: 'Broad-shelled Tortoise', code: '2016', group: 'reptile-amphibian' },
  { commonName: 'Common Long-necked Tortoise', code: '2017', group: 'reptile-amphibian' },
  { commonName: 'Murray River Tortoise', code: '2034', group: 'reptile-amphibian' },
  { commonName: 'Marbled Gecko', code: '2126', group: 'reptile-amphibian' },
  { commonName: 'Central Bearded Dragon', code: '2204', group: 'reptile-amphibian' },
  { commonName: 'Eastern Bearded Dragon', code: '2177', group: 'reptile-amphibian' },
  { commonName: "Gippsland Water Dragon", code: '2919', group: 'reptile-amphibian' },
  { commonName: 'Mountain Dragon', code: '2182', group: 'reptile-amphibian' },
  { commonName: 'Sand Goanna', code: '2271', group: 'reptile-amphibian' },
  { commonName: "Rosenberg's Goanna", code: '2287', group: 'reptile-amphibian' },
  { commonName: 'Tree Goanna', code: '2283', group: 'reptile-amphibian' },
  { commonName: 'Blotched Blue-tongued Lizard', code: '2578', group: 'reptile-amphibian' },
  { commonName: 'Common Blue-tongued Lizard', code: '2580', group: 'reptile-amphibian' },
  { commonName: 'Eastern Water Skink', code: '2557', group: 'reptile-amphibian' },
  { commonName: 'Garden Skink', code: '2451', group: 'reptile-amphibian' },
  { commonName: 'Stumpy-tailed Lizard (Shingleback)', code: '2583', group: 'reptile-amphibian' },
  { commonName: 'Carpet Python', code: '2969', group: 'reptile-amphibian' },
  { commonName: 'Common Death Adder', code: '2640', group: 'reptile-amphibian' },
  { commonName: 'Highland Copperhead', code: '2972', group: 'reptile-amphibian' },
  { commonName: 'Lowland Copperhead', code: '2973', group: 'reptile-amphibian' },
  { commonName: 'Red-bellied Black Snake', code: '2693', group: 'reptile-amphibian' },
  { commonName: 'Tiger Snake', code: '2681', group: 'reptile-amphibian' },
  { commonName: 'Eastern Brown Snake', code: '2699', group: 'reptile-amphibian' },
  { commonName: 'Western Brown Snake', code: '2698', group: 'reptile-amphibian' },
  { commonName: 'White-lipped Snake', code: '2665', group: 'reptile-amphibian' },
  { commonName: 'Yellow-faced Whip Snake', code: '2655', group: 'reptile-amphibian' },
  { commonName: 'Green Turtle', code: '2007', group: 'reptile-amphibian' },
  { commonName: 'Leathery Turtle', code: '2013', group: 'reptile-amphibian' },
  { commonName: 'Loggerhead Turtle', code: '2004', group: 'reptile-amphibian' },
];

const codeByName = new Map(
  VIC_SPECIES_CODES.map((entry) => [entry.commonName.toLowerCase(), entry.code])
);

/**
 * Look up the DEECA species code for a WildTrack360 species common name.
 * Returns undefined if not found - per the Wildlife Code Book's own guidance,
 * leave the Species Code field blank on the record sheet in that case and
 * use the common name with a "sp." qualifier if identification is uncertain.
 */
export function lookupVicSpeciesCode(commonName: string): string | undefined {
  return codeByName.get(commonName.trim().toLowerCase());
}
